### ISSUE TITLE
Reset password / re3gistry 2.6.0

### ISSUE THREAD

**Issue by k-eight-v** [ec-jrc/re3gistry#442]
I had a account which i made at the beginning of the installation. 
Inside database i have this account - i got in with no problems (admin panel)
Tried to reset password - said : "This user is NOT available in the database.", inside database i see that modification date was when i tried to reset password. Could not change it or reset it and now i cant get  in anymore. 

![Screenshot 2024-07-02 at 14 53 03](https://github.com/ec-jrc/re3gistry/assets/129046182/85c17a75-66dd-494b-bf70-4548a1142f6f)

**Comment by iratigarzon** [comment]
Dear @k-eight-v,

I have been investigating this issue, and it does not occur in our local instance. The problem might be originating from the email server. If you notice that modifications have been made in the database but the error still appears, it is likely due to an exception caused by the email server's inability to connect to the SMTP. The system attempts to send the email, but since it is not possible, you see the generic error shown in the picture.

Could you please check your email server? If the problem persists, do not hesitate to contact us.

Best regards,
Irati

**Comment by k-eight-v** [comment]
Thank you, fixed my "MAIL" conf inside tomcat/webapps/re3gistry2/WEB-INF/classes/configurations_files
But i faced new problem : 
after got mail and the key - logged in , but if i want to change password - the button does nothing : 

![Screenshot 2024-07-10 at 09 19 56](https://github.com/ec-jrc/re3gistry/assets/129046182/701e3122-1603-443f-acf5-c12880944626)

**Comment by k-eight-v** [comment]
Log from tomcat : 

Caused by: java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key changepassword.new.password
	at java.util.ResourceBundle.getObject(ResourceBundle.java:450) ~[?:1.8.0_265]
	at java.util.ResourceBundle.getString(ResourceBundle.java:407) ~[?:1.8.0_265]
	at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at javax.el.BeanELResolver.invoke(BeanELResolver.java:152) ~[el-api.jar:3.0.FR]
	at org.apache.jasper.el.JasperELResolver.invoke(JasperELResolver.java:163) ~[jasper.jar:9.0.90]
	at org.apache.el.parser.AstValue.getValue(AstValue.java:158) ~[jasper-el.jar:9.0.90]
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:169) ~[jasper-el.jar:9.0.90]
	at org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate(PageContextImpl.java:690) ~[jasper.jar:9.0.90]
	at org.apache.jsp.jsp.userProfile_jsp._jspService(userProfile_jsp.java:1247) ~[?:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:67) ~[jasper.jar:9.0.90]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623) ~[servlet-api.jar:4.0.FR]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466) ~[jasper.jar:9.0.90]

**Comment by iratigarzon** [comment]
Dear @k-eight-v,

Thank you for providing the Tomcat logs. I see there is an issue with a missing key in the ResourceBundle. Could you please let me know which language you are trying to change the password in? This will allow me to provide you with a functional ResourceBundle to use in your local instance.

Best regards,

Irati.

**Comment by k-eight-v** [comment]
English

**Comment by iratigarzon** [comment]
Dear @k-eight-v,

To set up the correct file, you need to navigate to dist/app/re3gistry2/WEB-INF/classes/localizations/LocalizationBundle_en.properties and replace its contents with the information from this file: 
[LocalizationBundle_en.txt](https://github.com/user-attachments/files/16174010/LocalizationBundle_en.txt).

Once you have modified that file, click the "Change Password" button. A pop-up will appear, allowing you to change the password.
![Captura](https://github.com/ec-jrc/re3gistry/assets/127838239/e89888aa-0c35-4022-905c-9d46ca0d338f)

Please note that this issue has been included in the milestone for the next version, which aims to fix the ResourceBundle problem for all languages.

Best regards,

Irati

**Comment by k-eight-v** [comment]
Thank you very much! Working

**Comment by iratigarzon** [comment]
I am reopening this issue as it is included in the milestone for the upcoming version 2.6.1. The issue will be closed once this version is available.
